[kombu.mixins - WARNING] Connection to broker lost, trying to re-establish connection...
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/kombu/mixins.py", line 174, in run
	(for _ in self.consume(limit=None, **kwargs):)
File "/usr/local/lib/python3.9/dist-packages/kombu/mixins.py", line 196, in consume
	(conn.drain_events(timeout=safety_interval))
File "/usr/local/lib/python3.9/dist-packages/kombu/connection.py", line 341, in drain_events
	(return self.transport.drain_events(self.connection, **kwargs))
File "/usr/local/lib/python3.9/dist-packages/kombu/transport/pyamqp.py", line 171, in drain_events
	(return connection.drain_events(**kwargs))
File "/usr/local/lib/python3.9/dist-packages/amqp/connection.py", line 526, in drain_events
	(while not self.blocking_read(timeout):)
File "/usr/local/lib/python3.9/dist-packages/amqp/connection.py", line 532, in blocking_read
	(return self.on_inbound_frame(frame))
File "/usr/local/lib/python3.9/dist-packages/amqp/method_framing.py", line 77, in on_frame
	(callback(channel, msg.frame_method, msg.frame_args, msg))
File "/usr/local/lib/python3.9/dist-packages/amqp/connection.py", line 538, in on_inbound_method
	(return self.channels[channel_id].dispatch_method())
File "/usr/local/lib/python3.9/dist-packages/amqp/abstract_channel.py", line 156, in dispatch_method
	(listener(*args))
File "/usr/local/lib/python3.9/dist-packages/amqp/channel.py", line 1629, in _on_basic_deliver
	(fun(msg))
File "/usr/local/lib/python3.9/dist-packages/kombu/messaging.py", line 656, in _receive_callback
	(return on_m(message) if on_m else self.receive(decoded, message))
File "/usr/local/lib/python3.9/dist-packages/kombu/messaging.py", line 622, in receive
	([callback(body, message) for callback in callbacks])
File "/usr/local/lib/python3.9/dist-packages/kombu/messaging.py", line 622, in <listcomp>
	([callback(body, message) for callback in callbacks])
File "/usr/local/lib/python3.9/dist-packages/hijiki/broker/hijiki_rabbit.py", line 147, in process_message
	(message.ack())
File "/usr/local/lib/python3.9/dist-packages/kombu/message.py", line 126, in ack
	(self.channel.basic_ack(self.delivery_tag, multiple=multiple))
File "/usr/local/lib/python3.9/dist-packages/amqp/channel.py", line 1407, in basic_ack
	(return self.send_method())
File "/usr/local/lib/python3.9/dist-packages/amqp/abstract_channel.py", line 70, in send_method
	(conn.frame_writer(1, self.channel_id, sig, args, content))
File "/usr/local/lib/python3.9/dist-packages/amqp/method_framing.py", line 186, in write_frame
	(write(buffer_store.view[:offset]))
File "/usr/local/lib/python3.9/dist-packages/amqp/transport.py", line 347, in write
	(self._write(s))
File "/usr/local/lib/python3.9/dist-packages/gevent/_socketcommon.py", line 699, in sendall
	(return _sendall(self, data_memory, flags))
File "/usr/local/lib/python3.9/dist-packages/gevent/_socketcommon.py", line 409, in _sendall
	(timeleft = __send_chunk(socket, chunk, flags, timeleft, end))
File "/usr/local/lib/python3.9/dist-packages/gevent/_socketcommon.py", line 338, in __send_chunk
	(data_sent += socket.send(chunk, flags))
File "/usr/local/lib/python3.9/dist-packages/gevent/_socketcommon.py", line 722, in send
	(return self._sock.send(data, flags))
ConnectionResetError: [Errno 104] Connection reset by peer